repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "ipynb$"
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ".ipython"
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: ".ipython"
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: "(setup.py)|(conf.py)|(.ipython)"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        exclude: ".ipython"
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.9.0
    hooks:
      - id: nbqa-isort
        args: [--nbqa-mutate]
      - id: nbqa-black
        args: [--nbqa-mutate]
      - id: nbqa-mypy
        args: [--nbqa-mutate]
      - id: nbqa-flake8
        args: [--nbqa-mutate]
